### ISSUE TITLE
Unable to receive the json responce to the source

### ISSUE THREAD

**Issue by Lasith650** [siddhi-io/siddhi-io-http#80] opened 2018-09-25 07:31 UTC
Description:
I am trying to connect to the github api through a siddhi app using the bellow code,

@App:name("RequestResponseSample")
@App:description('This sample siddhi app demonstrates how to use transport properties along with request sink and response source') 

define stream regStream (id String);   

@sink(type='http-request', publisher.url='http://api.github.com/repos/wso2/product-sp/releases',
method='POST',
chunk.disabled='true', 
 sink.id='reg-company',
@map(type='json', @payload("""{"id":"{{id}}"}""")))
define stream requestStream (id string);

-- source to receive successful responses (which have 2xx status codes)
@source(type='http-response' , sink.id='reg-company', http.status.code='200',
@map(type='json', @attributes(tag_name='$.tag_name'))) 
define stream responseStream(tag_name string);

-- source to receive the responses with 4xx status codes
@source(type='http-response' , sink.id='reg-company', http.status.code='403' ,
@map(type='text', regex.A='((.|\n)*)', @attributes(message='A[1]')))  
define stream responseStream4xx(message string);

@sink(type='log') 
define stream logStream(tag_name string);

from regStream
select id
insert into requestStream;

from responseStream
select *
insert into logStream;

But I am not getting a response. It displays an error message saying that the channel is inactive 

Bellow is the response I received when I requested through "Postman"

![image](https://user-images.githubusercontent.com/23395897/45999321-f4ea8a00-c0c2-11e8-8b15-58a0e47ac24e.png)
@minudika

**Comment by minudika** [comment] 2018-10-07 08:47
Tried to reproduce this but could not reproduce the exact issue.
When calling to the given endpoint we encountered the issue #83.

**Comment by mohanvive** [comment] 2019-08-29 08:58
Closing the issue since related redirection issue is handled by another [ticket](https://github.com/siddhi-io/siddhi-io-http/issues/83) ...

**Closed by mohanvive** 2019-08-29 08:58 UTC
Labels: priority/normal
